version: "3"

networks:
  backend:
    driver: bridge

services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb-server
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb/cupitor/data:/bitnami
    networks:
      - backend
    environment:
      - MONGO_URL=mongodb://mongodb-server:27017/cupitor-db

  frontend:
    image: trexsatya/cupitor-frontend-vuejs:latest
    container_name: cupitor-frontend
    environment:
      - __js_config__API_URL=//cupitor-api:8080/api
      - __js_config__imageCdnUrl=//cupitor.online:8080/images
    ports:
      - "80:80"
    networks:
      - backend
    
  backend:
    image: trexsatya/cupitor-backend-springboot:latest
    container_name: cupitor-api
    environment:
      - users=${USERS}
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on: 
      - mongodb
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure


