version: "3"

networks:
  backend:
    driver: bridge

services:
  fix-mongodb-permissions:
    image: bitnami/mongodb:latest
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - /var/lib/mongodb/cupitor/data:/bitnami

  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb-server
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb/cupitor/data:/bitnami
    networks:
      - backend
    depends_on:
      - fix-mongodb-permissions

  frontend:
    image: trexsatya/cupitor-frontend-vuejs:latest
    container_name: cupitor-frontend
    environment:
      - __js_config__API_URL=http://localhost:8080/api
      - __js_config__imageCdnUrl=https://storage.googleapis.com/cupitor-220103.appspot.com/images/
    ports:
      - "80:80"
    networks:
      - backend
    
  backend:
    image: trexsatya/cupitor-backend-springboot:latest
    logging:
        driver: "json-file"
        options:
            max-file: "2"
            max-size: "2m"
    container_name: cupitor-api
    environment:
      - users=${USERS}
      - MONGO_HOST=mongodb-server
      - MONGO_DB_NAME=cupitor-db  
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on: 
      - mongodb
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure


