// Live filmot.com fetching with an on-disk page cache. The candidate-selection
// logic (channel exclusion, manual-first, quota) is a pure function so it can be
// unit-tested; fetch + cache is a thin shell.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";

const BASE = "https://filmot.com";

const DEFAULT_UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

// Search-results page URL for a quoted word. `page` is filmot's 1-based results
// page (the number after the query in the path).
export function buildSearchUrl(word, lang = "sv", page = 1) {
  const quoted = `%22${encodeURIComponent(word)}%22`;
  return `${BASE}/search/${quoted}/${page}?lang=${lang}`;
}

// The clean terms to search filmot for, derived from an expanded vocab line:
// each `|`-separated alternative, trimmed, >=3 chars, deduped (order preserved).
// A single idiom phrase stays one term.
export function searchTermsForWord(expanded, { minLen = 3 } = {}) {
  const seen = new Set();
  const out = [];
  for (const raw of String(expanded || "").split("|")) {
    const t = raw.trim();
    if (t.length < minLen || seen.has(t)) continue;
    seen.add(t);
    out.push(t);
  }
  return out;
}

// filmot serves an hCaptcha "Verify You're Human" page to unauthenticated
// requests. Detect it so the CLI can warn (set filmotCookie) instead of silently
// recording zero hits. IMPORTANT: normal filmot pages also load the hCaptcha
// library, so a bare "hcaptcha" mention is NOT a challenge — only the dedicated
// challenge page (no results, plus its captcha container / "Verify You're Human"
// title) counts.
export function isChallengePage(html) {
  const s = String(html || "");
  // A page with video results / a transcript is a real page, whatever scripts it loads.
  if (/id="vcard_|id="subtitlesIn"/.test(s)) return false;
  return /captcha-container|verify\s+you.{0,8}re\s+human/i.test(s);
}

// Choose which videos to fetch transcripts for. `excludeChannels` are a HARD
// drop; `blacklistChannels` are a SOFT de-prioritize (used only to fill the quota
// after better options). Channel is resolved via `channelOf(videoId)`; an unknown
// channel is treated as neither excluded nor blacklisted (kept, not demoted).
//
// Ordering is caption-primary, blacklist-secondary (a two-key stable sort):
//   1 manual / not-blacklisted   2 manual / blacklisted
//   3 auto   / not-blacklisted   4 auto   / blacklisted
// With no blacklist set this collapses to plain manual-first. With
// `preferManual: false` caption drops out and blacklist is the sole key.
export function selectCandidates(cards, opts = {}) {
  const {
    max = 5,
    excludeChannels = [],
    blacklistChannels = [],
    channelOf = () => undefined,
    preferManual = true,
  } = opts;
  const blocked = new Set(excludeChannels);
  const soft = new Set(blacklistChannels);
  const isBlacklisted = (c) => {
    const ch = channelOf(c.videoId);
    return ch && soft.has(ch) ? 1 : 0;
  };
  const kept = (cards || []).filter((c) => {
    const ch = channelOf(c.videoId);
    return !(ch && blocked.has(ch)); // unknown channel (falsy) => keep
  });
  const ordered = kept
    .map((c, i) => ({ c, i }))
    .sort((x, y) => {
      if (preferManual) {
        const ax = x.c.isAutoGenerated ? 1 : 0;
        const ay = y.c.isAutoGenerated ? 1 : 0;
        if (ax !== ay) return ax - ay;
      }
      const bx = isBlacklisted(x.c);
      const by = isBlacklisted(y.c);
      if (bx !== by) return bx - by;
      return x.i - y.i; // keep input order within a tier (stable)
    })
    .map((w) => w.c);
  return max && max > 0 ? ordered.slice(0, max) : ordered;
}

// Count candidates that are neither hard-excluded nor soft-blacklisted — the
// "others" whose sufficiency decides whether pagination should reach for more
// pages before falling back to blacklisted channels. Unknown channels count.
export function nonBlacklistedCount(cards, opts = {}) {
  const { blacklistChannels = [], excludeChannels = [], channelOf = () => undefined } = opts;
  const soft = new Set(blacklistChannels);
  const blocked = new Set(excludeChannels);
  let n = 0;
  for (const c of cards || []) {
    const ch = channelOf(c.videoId);
    if (ch && (blocked.has(ch) || soft.has(ch))) continue;
    n++;
  }
  return n;
}

// --- fetch + cache ---------------------------------------------------------

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function cachePathFor(cacheDir, url) {
  const h = createHash("sha1").update(url).digest("hex").slice(0, 16);
  return join(cacheDir, `${h}.html`);
}

// GET a filmot page as text, using the disk cache when present. Throttled +
// retried. Pass `cookie` (your logged-in filmot session) + matching `userAgent`
// to get past filmot's hCaptcha wall. `fetchFn` is injectable for testing.
// Challenge pages are never cached, so they don't poison later runs.
export async function fetchPage(url, opts = {}) {
  const {
    cacheDir,
    fetchFn = fetch,
    delayMs = 1500,
    tries = 3,
    backoffMs = 2000,
    force = false,
    cookie = "",
    userAgent = DEFAULT_UA,
  } = opts;

  if (cacheDir && !force) {
    const p = cachePathFor(cacheDir, url);
    if (existsSync(p)) {
      const cached = readFileSync(p, "utf8");
      // Ignore captcha pages a prior (cookie-less) run may have cached, so the
      // cache self-heals once a valid cookie is set.
      if (!isChallengePage(cached)) return cached;
    }
  }

  const headers = {
    "User-Agent": userAgent,
    "Accept-Language": "sv,en;q=0.8",
  };
  if (cookie) headers.Cookie = cookie;

  let lastErr;
  for (let attempt = 0; attempt < tries; attempt++) {
    try {
      if (delayMs) await sleep(delayMs);
      const res = await fetchFn(url, { headers });
      if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
      const html = await res.text();
      if (cacheDir && !isChallengePage(html)) {
        mkdirSync(cacheDir, { recursive: true });
        writeFileSync(cachePathFor(cacheDir, url), html);
      }
      return html;
    } catch (e) {
      lastErr = e;
      if (attempt < tries - 1) await sleep(backoffMs * (attempt + 1));
    }
  }
  throw lastErr;
}
