import { collectRankedPool } from "./filmot-collect.js";

// Scripted fetcher: getPage returns a JSON string of the cards for that URL, and
// we inject JSON.parse as the "parser" so the test is decoupled from filmot HTML
// (that parsing is covered in filmot-parse.test.js). Channels come from a fixture.
function harness(pagesByUrl, channelOfId) {
  const calls = [];
  const getPage = async (url) => {
    calls.push(url);
    return JSON.stringify(pagesByUrl[url] || []);
  };
  const parseSearchResultsFn = (html) => JSON.parse(html);
  const resolveChannelFn = async (id, { cache }) => {
    cache[id] = channelOfId[id];
    return cache[id];
  };
  return { calls, getPage, parseSearchResultsFn, resolveChannelFn };
}

const card = (videoId, isAutoGenerated = false) => ({
  videoId,
  isAutoGenerated,
  transcriptUrl: `/t/${videoId}`,
  title: videoId,
});

// filmot search URL for term "x" at page p (matches buildSearchUrl).
const url = (p) => `https://filmot.com/search/%22x%22/${p}?lang=sv`;

const baseCfg = { lang: "sv", maxItemsPerWord: 2, maxSearchPages: 3, preferManualCaptions: true };

describe("collectRankedPool", () => {
  test("stops paging once enough non-blacklisted candidates exist (page 1 only)", async () => {
    const h = harness(
      { [url(1)]: [card("a"), card("b")] },
      { a: "Good", b: "Good" }
    );
    const cache = {};
    const ranked = await collectRankedPool({
      terms: ["x"],
      cfg: baseCfg,
      channelCache: cache,
      blacklistChannels: ["BL"],
      ...h,
    });
    expect(h.calls).toEqual([url(1)]); // never fetched page 2
    expect(ranked.map((c) => c.videoId).sort()).toEqual(["a", "b"]);
  });

  test("pages further when page 1 is all blacklisted, until non-blacklisted are found", async () => {
    const h = harness(
      { [url(1)]: [card("p1a"), card("p1b")], [url(2)]: [card("p2a"), card("p2b")] },
      { p1a: "BL", p1b: "BL", p2a: "Good", p2b: "Good" }
    );
    const ranked = await collectRankedPool({
      terms: ["x"],
      cfg: baseCfg,
      channelCache: {},
      blacklistChannels: ["BL"],
      ...h,
    });
    expect(h.calls).toEqual([url(1), url(2)]); // paged to 2 to find non-BL
    // non-blacklisted ranked ahead of blacklisted; top `max` are the two Good ones
    expect(ranked.slice(0, 2).map((c) => c.videoId).sort()).toEqual(["p2a", "p2b"]);
  });

  test("respects maxSearchPages and falls back to blacklisted candidates", async () => {
    const h = harness(
      {
        [url(1)]: [card("a")],
        [url(2)]: [card("b")],
        [url(3)]: [card("c")],
      },
      { a: "BL", b: "BL", c: "BL" }
    );
    const ranked = await collectRankedPool({
      terms: ["x"],
      cfg: { ...baseCfg, maxSearchPages: 2 },
      channelCache: {},
      blacklistChannels: ["BL"],
      ...h,
    });
    expect(h.calls).toEqual([url(1), url(2)]); // capped at 2 pages, page 3 never fetched
    expect(ranked.map((c) => c.videoId).sort()).toEqual(["a", "b"]); // blacklisted used as fallback
  });

  test("stops paging when a page returns no new results", async () => {
    const h = harness(
      { [url(1)]: [card("a")], [url(2)]: [card("a")] }, // page 2 repeats page 1
      { a: "BL" }
    );
    const ranked = await collectRankedPool({
      terms: ["x"],
      cfg: baseCfg,
      channelCache: {},
      blacklistChannels: ["BL"],
      ...h,
    });
    expect(h.calls).toEqual([url(1), url(2)]); // fetched p2, saw nothing new, stopped
    expect(ranked.map((c) => c.videoId)).toEqual(["a"]);
  });
});
