import {
  buildSearchUrl,
  selectCandidates,
  nonBlacklistedCount,
  searchTermsForWord,
  isChallengePage,
  fetchPage,
} from "./filmot-fetch.js";

describe("searchTermsForWord", () => {
  test("splits an expanded line into clean, deduped alternatives (>=3 chars)", () => {
    expect(searchTermsForWord("medfölja|åtfölja|följeslagare")).toEqual([
      "medfölja",
      "åtfölja",
      "följeslagare",
    ]);
  });

  test("keeps a single idiom phrase as one term", () => {
    expect(searchTermsForWord("bita i det sura äpplet")).toEqual([
      "bita i det sura äpplet",
    ]);
  });

  test("drops short/padded alternatives and dedupes", () => {
    expect(searchTermsForWord(" ha |sova|se|sova")).toEqual(["sova"]);
  });
});

describe("isChallengePage", () => {
  test("detects the real challenge page by container / verify-human title", () => {
    expect(
      isChallengePage("<title>Verify You&#039;re Human</title><div class='captcha-container'>x</div>")
    ).toBe(true);
    expect(isChallengePage("<title>Verify You're Human</title>")).toBe(true);
  });

  test("does NOT flag a real results page that merely loads the hCaptcha library", () => {
    expect(
      isChallengePage('<div id="vcard_abc">results</div><script src="hcaptcha.js"></script>')
    ).toBe(false);
    expect(isChallengePage('<div id="subtitlesIn">lines</div>')).toBe(false);
    // a legitimate zero-result search (no cards, no captcha container) is not a challenge
    expect(isChallengePage("<div>No results found</div>")).toBe(false);
  });
});

describe("fetchPage cookie/UA", () => {
  test("sends the Cookie header and custom User-Agent when provided", async () => {
    let seen = null;
    const fetchFn = async (url, init) => {
      seen = init;
      return { ok: true, text: async () => "<html>ok</html>" };
    };
    const html = await fetchPage("https://filmot.com/x", {
      fetchFn,
      delayMs: 0,
      cookie: "sess=abc; other=1",
      userAgent: "MyUA/1.0",
    });
    expect(html).toBe("<html>ok</html>");
    expect(seen.headers.Cookie).toBe("sess=abc; other=1");
    expect(seen.headers["User-Agent"]).toBe("MyUA/1.0");
  });
});

describe("buildSearchUrl", () => {
  test("builds a quoted, encoded filmot search url with lang", () => {
    const url = buildSearchUrl("åtgång", "sv");
    expect(url).toContain("filmot.com/search/");
    expect(url).toContain("%22" + encodeURIComponent("åtgång") + "%22");
    expect(url).toContain("lang=sv");
  });

  test("defaults to page 1", () => {
    const q = "%22" + encodeURIComponent("åtgång") + "%22";
    expect(buildSearchUrl("åtgång", "sv")).toContain(`/${q}/1?lang=sv`);
  });

  test("emits the requested page number", () => {
    const q = "%22" + encodeURIComponent("åtgång") + "%22";
    expect(buildSearchUrl("åtgång", "sv", 3)).toContain(`/${q}/3?lang=sv`);
  });
});

describe("selectCandidates", () => {
  const cards = [
    { videoId: "a", isAutoGenerated: false },
    { videoId: "b", isAutoGenerated: true },
    { videoId: "c", isAutoGenerated: false },
    { videoId: "d", isAutoGenerated: true },
  ];
  const channelOf = (id) =>
    ({ a: "Good", b: "Bad", c: "Good", d: "Good" }[id]);

  test("excludes blocked channels, prefers manual, respects max", () => {
    const out = selectCandidates(cards, {
      max: 2,
      excludeChannels: ["Bad"],
      channelOf,
    });
    expect(out.map((c) => c.videoId)).toEqual(["a", "c"]);
  });

  test("uses auto-generated only to fill the remaining quota", () => {
    const out = selectCandidates(cards, {
      max: 3,
      excludeChannels: ["Bad"],
      channelOf,
    });
    expect(out.map((c) => c.videoId)).toEqual(["a", "c", "d"]); // d (auto) tops up
  });

  test("keeps cards whose channel is unknown (unresolved)", () => {
    const out = selectCandidates([{ videoId: "z", isAutoGenerated: false }], {
      max: 5,
      excludeChannels: ["Bad"],
      channelOf: () => undefined,
    });
    expect(out.map((c) => c.videoId)).toEqual(["z"]);
  });

  test("preferManual=false keeps original order", () => {
    const out = selectCandidates(cards, { max: 2, preferManual: false });
    expect(out.map((c) => c.videoId)).toEqual(["a", "b"]);
  });
});

describe("selectCandidates with blacklist (soft de-prioritize)", () => {
  // a: manual/non-BL, b: manual/BL, c: auto/non-BL, d: auto/BL.
  // Input order lists blacklisted before non-blacklisted WITHIN each caption
  // group, so a correct sort must reorder them (not just rely on stable order).
  const cards = [
    { videoId: "b", isAutoGenerated: false },
    { videoId: "a", isAutoGenerated: false },
    { videoId: "d", isAutoGenerated: true },
    { videoId: "c", isAutoGenerated: true },
  ];
  const channelOf = (id) =>
    ({ a: "NonBL", b: "BL", c: "NonBL", d: "BL" }[id]);

  test("orders manual/non-BL → manual/BL → auto/non-BL → auto/BL", () => {
    const out = selectCandidates(cards, {
      max: 4,
      blacklistChannels: ["BL"],
      channelOf,
    });
    expect(out.map((c) => c.videoId)).toEqual(["a", "b", "c", "d"]);
  });

  test("a blacklisted manual caption outranks a non-blacklisted auto one", () => {
    const out = selectCandidates(
      [
        { videoId: "auto-good", isAutoGenerated: true },
        { videoId: "manual-bad", isAutoGenerated: false },
      ],
      { max: 2, blacklistChannels: ["BL"], channelOf: (id) => (id === "manual-bad" ? "BL" : "NonBL") }
    );
    expect(out.map((c) => c.videoId)).toEqual(["manual-bad", "auto-good"]);
  });

  test("excludeChannels wins over blacklist: a channel in both is dropped", () => {
    const out = selectCandidates(cards, {
      max: 4,
      excludeChannels: ["BL"],
      blacklistChannels: ["BL"],
      channelOf,
    });
    expect(out.map((c) => c.videoId)).toEqual(["a", "c"]); // b,d dropped entirely
  });

  test("empty blacklist reproduces the plain manual-first order (no reordering within a tier)", () => {
    const out = selectCandidates(cards, { max: 4, blacklistChannels: [], channelOf });
    expect(out.map((c) => c.videoId)).toEqual(["b", "a", "d", "c"]);
  });
});

describe("nonBlacklistedCount", () => {
  const channelOf = (id) =>
    ({ a: "NonBL", b: "BL", x: "Excluded" }[id]); // z → undefined (unknown)
  const cards = [
    { videoId: "a" },
    { videoId: "b" },
    { videoId: "x" },
    { videoId: "z" },
  ];

  test("counts cards that are neither excluded nor blacklisted (unknown counts)", () => {
    expect(
      nonBlacklistedCount(cards, {
        blacklistChannels: ["BL"],
        excludeChannels: ["Excluded"],
        channelOf,
      })
    ).toBe(2); // a (NonBL) + z (unknown); b blacklisted, x excluded
  });

  test("with no blacklist/exclude, every card counts", () => {
    expect(nonBlacklistedCount(cards, { channelOf })).toBe(4);
  });
});
